### PR TITLE
feat(cloud-sync): updated

### PR DESCRIPTION
**Pull request by Gabe616**
- add security + warnibng thing

### CODE REVIEW

**Comment by Gabe616** [comment]
@FieryFlames could this get resolved already please, every time I change something in my main branch I have to somehow fix this PR

**Comment by FieryFlames** [comment]
I can't merge PRs to vendetta, ask beef about merging your PR to vendetta and then we can proxy cloudsync

**Comment by Gabe616** [comment]
will be updating the backend's database later, don't proxy yet

**Comment by Gabe616** [comment]
blehhh
image

**Pull request merged**
